POST http://localhost:3333/subscriptions
Content-Type: application/json
 
{
  "name": "John Doe",
  "email": "pedro@gmail.com"
}

###

GET  http://localhost:3333/invites/pedro123


###

GET http://localhost:3333/subscribers/pedro123/ranking/clicks